### ISSUE TITLE
Fire.html Page displays incorrect page 

### ISSUE THREAD

**Issue by Samuel-L-James** [MaribelBautistaTena/Elemental#4]
When the fire.html is accessed from the main list the incorrect page photo is shown and the photo for the water,png page is displayed

**Comment by MaribelBautistaTena** [comment]
This page now contains the right photo file (fire.png).

**Comment by Samuel-L-James** [comment]
I am rewording my issue to more accurately represent the bug as follows,
When the fire.html is accessed from list.html the incorrect page photo is shown and the photo for the water,png page is displayed.
