### ISSUE TITLE
Air.html page crashes returning to the main list

### ISSUE THREAD

**Issue by Samuel-L-James** [MaribelBautistaTena/Elemental#5]
The air.html page will crash when redirected back to the main list page

**Comment by MaribelBautistaTena** [comment]
The air.html page now redirects to the correct main list page (list.html).

**Comment by oppenheip** [comment]
This is not an accurate bug report. The page does not crash. Maribel figured out how to fix it though.

**Comment by Samgotdam** [comment]
Is there any way I can reformat my issues for the Github assignment this
week to better describe the bugs that were discovered and work on my
formatting? I completely understand if I can not alter the issues because
the assignment has already been completed and submitted.

**Comment by Samuel-L-James** [comment]
I am rewording my entry to represent a mroe accurate bug report as follows
The air.html page's Return to the Elements List button incorrectly redirects the user to lits.html rather than list.html
