### ISSUE TITLE
Earth.html returns to the incorrect screen

### ISSUE THREAD

**Issue by Samuel-L-James** [MaribelBautistaTena/Elemental#6]
The earth.html page returns to the incorrect screen when redirected to the main page

**Comment by MaribelBautistaTena** [comment]
The link on the earth.html page is now fixed and will go to the list.html page.

**Comment by oppenheip** [comment]
"The earth.html page returns to the incorrect screen when _redirected to the main page_." This isn't an accurate bug report, but Maribel figured out what to fix nonetheless. It should return to the list page.

**Comment by Samuel-L-James** [comment]
I am fixing my wording for this issue as follows

When you click the link on the earth.html page to return to the list.html page it takes you to the index.html page.
